-- Migration Script: MySQL to Supabase (PostgreSQL)
-- Developed by Jules for Antigravity AI

-- Clean up existing objects
DROP TABLE IF EXISTS users CASCADE;
DROP TYPE IF EXISTS user_role;

-- 1. Create custom ENUM type for roles
CREATE TYPE user_role AS ENUM ('user', 'admin');

-- 2. Create users table with PostgreSQL optimized types
-- Preference: bigint for IDs and text for strings
-- Double quotes are used for camelCase identifiers like "refreshToken"
CREATE TABLE users (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname text NOT NULL,
    lastname text NOT NULL,
    email text NOT NULL UNIQUE,
    username text NOT NULL UNIQUE,
    password text NOT NULL,
    role user_role NOT NULL DEFAULT 'user',
    "refreshToken" text
);

-- 3. Import initial data from MySQL dump
-- We omit ID to let Postgres handle the sequence, or include it if specific IDs are needed
INSERT INTO users (firstname, lastname, email, username, password, role) VALUES
('Juan', 'Pérez', 'juanperez@example.com', 'juanp', '1234', 'user'),
('María', 'López', 'marialopez@example.com', 'marial', '1234', 'user'),
('Kevin', 'Anillo', 'kevin2000urba@gmail.com', 'kevin23', '1234', 'user');

-- 4. Synchronize the ID sequence
-- This is crucial to avoid "duplicate key value violates unique constraint" errors
-- after manual data imports with explicit IDs or if the sequence gets out of sync.
SELECT setval(pg_get_serial_sequence('users', 'id'), coalesce(max(id), 1)) FROM users;

-- Verify migration
-- SELECT * FROM users;
