-- Supabase Migration: MySQL users table to PostgreSQL

-- 1. Create custom enum type for roles if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('user', 'admin');
    END IF;
END $$;

-- 2. Create the users table
CREATE TABLE IF NOT EXISTS public.users (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname text NOT NULL,
    lastname text NOT NULL,
    email text NOT NULL,
    username text NOT NULL,
    password text NOT NULL,
    role user_role NOT NULL DEFAULT 'user',
    "refreshToken" text,
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

-- 3. Insert data from MySQL dump
INSERT INTO public.users (firstname, lastname, email, username, password, id, role, "refreshToken") VALUES
('Kevin','Anillo','kevin2000urba@gmail.com','kevin23','$2b$10$4dRFNKfEwnoqfUeAlopBIeYCeGDA/y5Js7RQ05Ao1XyJjhQXsobwu',3,'admin',NULL),
('elena','cordaba','elena@ejemplo.com','elenac','$2b$10$DLtMSFHE/4MKEvu/kLPqTOp7PTVw/R6i/flCvkRj.sK2ilit9OgbK',5,'user',NULL),
('kevin','anillo','anillocoba@gmail.com','anillo','$2b$10$qdusHNUmAub.8/XKW7HO1O1pXxPrBBtQMFzmix0BxAgxIRUAdZJqK',7,'user',NULL),
('hola','adios','hola@ejemplo.com','hola','$2b$10$NYg9JlY3Za1fe7FettSGFe53NSWMwWyIr/vlc3EpmFPBmVe5bq6Mq',9,'admin',NULL),
('patata','patata','patata@ejemplo.com','patata','$2b$10$A3BMUEb5yOxJJOgCMCCK9u46zdXN.gM7tlWswH9c.aR5eguRD1W66',10,'user',NULL),
('davinia','davinia','tu@ejemplo.com','davinia','$2b$10$DjV4koZcviPpCGi8bbG1POTsjxoitRuxYwODMXFyHqm3.aMkeCN62',12,'user',NULL),
('o','la','ola@ejemplo.com','ola','$2b$10$fivrYiWclgcQCe/xBCX7LeGN9o0cw1dyvtrUlP7dvbz1UfjMq5Xke',15,'user',NULL),
('prueba','p','userp@example.com','user','$2b$10$v2zRdNITAselqWrAWlmSxu/yZT3PpKlhac08zpqfuzpHZ0EtVplyy',16,'user',NULL),
('Admin','Super','admin@example.com','admin','$2b$10$di6UttHZsT0cZf0aja4.DOIKXYkW2x2nPjEivbs4DgPdSKNoo8kjG',23,'admin','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsImlhdCI6MTc2OTQ0MzgxMSwiZXhwIjoxNzcwMDQ4NjExfQ.iBzUCoSPdQIM50k9qzsMUR-gG43b6Zu-QLlAWa_q5eA'),
('Admin3','Super','admin3@example.com','admin3','Admin1234',26,'admin',NULL),
('Admin4','Super','admin4@example.com','admin4','Admin1234',28,'admin',NULL),
('mis','perez','misperez@gmail.com','misperez','$2b$10$RRZ4hvQD7bdrPFJAshTa9.JinJrOsgtipGEwqwzhNV/pk/bJqt9DC',29,'user','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjksImlhdCI6MTc2ODc3ODI1MSwiZXhwIjoxNzY5MzgzMDUxfQ.c1ZxtDqo3TRLOQn-yYYZdmjokEaZpjxTwxSQt8t4lOs'),
('Test','User','user_1768780224033@example.com','user_1768780224033','$2b$10$vHzHBFeouB.F3UUjNujPhum9cOVd7KDeVonGZYvbVsVfU/lNtSxna',30,'user',NULL),
('Test','User','user_1768780378615@example.com','user_1768780378615','$2b$10$HtdEQEUJXeMf8zOkHXpLJeIRh1BND/mIeY69It6dq/pU0dRMtJuHe',31,'user',NULL),
('Test','User','user_1768780491781@example.com','user_1768780491781','$2b$10$79Wqaz1NySUjaefx8GnJOuMIhQU9wOTyxTF/OXgnyljfIVqkQb9Di',32,'user',NULL),
('Test','User','user_1768780694896@example.com','user_1768780694896','$2b$10$3i9etr12fsHStpuxHoyEKuV9rL6RSLHz94mNyNJtY5fzjy8T7nEiS',33,'user',NULL),
('Test','User','user_1768781286191@example.com','user_1768781286191','$2b$10$UfVIxke731xaOmnLEuSfiue14cLV3i085Xzm8C1ME01MZkFG9Ihyi',34,'user',NULL),
('Test','User','user_1768781519545@example.com','user_1768781519545','$2b$10$ebZmgtjTeU2MmYjVbD7AKuJonGF8IPBnrMgIRqzD0DAHN5Vop4YoW',35,'user',NULL),
('Test','User','user_1768781628675@example.com','user_1768781628675','$2b$10$cR4Jp5hCz.jbe.0oZPyYYe5MJqlnfLFpUtZE4Z7lPgaKVp5ZyxkSe',36,'user',NULL),
('Test','User','user_1768782258321@example.com','user_1768782258321','$2b$10$Lkr0WVP7pPMtMgMn/numjuOcltEcrPFbSGtVFmCeAPVsfSNEcrgFK',37,'user',NULL),
('Test','User','user_1768782525362@example.com','user_1768782525362','$2b$10$g1yU.2S.m02sQpDNM7mJl.jpIO8c8.zuaA.CA4xP8tURrabTTPYDy',38,'user',NULL),
('Test','User','user_1768783230578@example.com','user_1768783230578','$2b$10$.pIPbe7wG81OGM8AGNyGe.R5//1MnCrO0Y1KBp7tE5iPtrLMcj7mO',39,'user',NULL),
('Test','User','user_1768783489274@example.com','user_1768783489274','$2b$10$Enp3kgLU/KAZyWT8yoMx3.RPlaBp5doGf3GB6ilP7YSHLUfyAwxpi',40,'user',NULL),
('Test','User','user_1768831331373@example.com','user_1768831331373','$2b$10$xcWjKTshRusrYPhBJGJNiOHbJ1gEINiVRI64oAPpL119hVZJxNaIW',41,'user',NULL),
('lucas','lucas','luca@l.com','lucas','$2b$10$wYZya1vKBzV3BGnab.WLK.8gGGuvqC4hjinxBEhUNlCPRTDmwsKle',42,'user','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDIsImlhdCI6MTc2OTM3NTA0MiwiZXhwIjoxNzY5OTc5ODQyfQ.cLFWWcUtlNupcdmvGdM1wrugssnwLdwR54twb_vqVgU'),
('Test','User','testuser_1769378325400@example.com','testuser_1769378325400','$2b$10$mvRVReIBPej5juDThvC8BOcdlWQ6AHaYWmg.AmTjUcN7Jr/DtjfQa',43,'user',NULL),
('Test','User','duplicate_1769378346866@example.com','user_1769378347548','$2b$10$RpbOFwUVR4aiTDdW5ypUteoS.8EZNebRgkLcWBA6ZmtieJ2h1/8RG',44,'user',NULL),
('Test','User','testuser_1769378430035@example.com','testuser_1769378430035','$2b$10$IP1aUWpYDSpkvo1KaYa5HOsB.inBdOPpDpJsCfpZcq7G66foYYZgq',46,'user',NULL),
('Test','User','duplicate_1769378439321@example.com','user_1769378440064','$2b$10$VItP5TNmyh5m4oW8qJdqt.Lfbnd7.ToMbakcY.KoBgVRIWF7kTVVS',47,'user',NULL),
('Test','User','testuser_1769378464952@example.com','testuser_1769378464952','$2b$10$jYqZzfCuRInulNXPHgYTYOPKwFwgIZQtndjCXf/ThEf0p7R3zIHIu',49,'user',NULL),
('Test','User','testuser_1769378560854@example.com','testuser_1769378560854','$2b$10$3yzILtWYOdyTNseyH1XrLOs1.dvHR59ouTCZV.gwEMTPVWxrVWtnS',52,'user',NULL),
('Test','User','testuser_1769378697234@example.com','testuser_1769378697234','$2b$10$2NNfpYNUpNE1wCR6QV1Syu6m2grLdQhCwMm033SC.iCNfPGSDlZY.',57,'user',NULL),
('Test','User','dup_1769378703774@example.com','u1_1769378704516','$2b$10$8WXJ4R14jbOIMBiK4JYlfubFZykEOl/T0hDYC3V3u7mCOnxrTYnim',58,'user',NULL),
('Test','User','testuser_1769379900013@example.com','testuser_1769379900013','$2b$10$LT73AXQv2yILFPIhIYUoYeCMMiQNSZpCzI9zeZVCMYq.nDUZSuZfu',60,'user',NULL),
('Test','User','dup_1769379906883@example.com','u1_1769379907272','$2b$10$TPPJ5/0eZYwz2KtP9EL/YOHRv6SVkfloaw8ZCTeYHksr4xGD59h.O',61,'user',NULL),
('Test','User','testuser_1769380227166@example.com','testuser_1769380227166','$2b$10$x1RtQlFR7X9/HVWFHHMXz.fC4Xy2hO.AO1MR1iigk2j5NPEYUQ4AS',62,'user',NULL),
('Test','User','dup_1769380233229@example.com','u1_1769380233606','$2b$10$Kqet92/TIYuBPYG38Qt.t.GNJ0hh3Om0ckWAoqcJuzkW8NuVWvrRy',63,'user',NULL),
('Test','User','testuser_1769380352287@example.com','testuser_1769380352287','$2b$10$89H9G7zmWHXaLKtfVc94wOcWCHIfd89gGLPcXNUMViOgrkNIIrEUq',64,'user',NULL),
('Test','User','dup_1769380358254@example.com','u1_1769380358617','$2b$10$srqPaHuzKvf20oizB2iOj.YU/NqVJgreOmXj/dtFLYtOYp0lNykTq',65,'user',NULL),
('Test','User','testuser_1769380710699@example.com','testuser_1769380710699','$2b$10$Ey0ea5jFtiSAvgUnYoNyX.BkQZc2IMMoOBLdFUNwgRiDeG5ztUOn2',66,'user',NULL),
('Test','User','dup_1769380717180@example.com','u1_1769380717535','$2b$10$4gdRdb1YWi4Mrht/xaKRMONttFTF2SeYOa9h.Jj4iz/UY33nT1N0e',67,'user',NULL),
('Test','User','testuser_1769381931968@example.com','testuser_1769381931968','$2b$10$h13KL1WIMIWZj6pMSn6f1.xVypfIqgb8v7El71LGOSQOjg8FWBCsy',68,'user',NULL),
('Test','User','dup_1769381938051@example.com','u1_1769381938432','$2b$10$DZWcsYJu/jr4.5AklWA2YOA8QvFVp.sya7q0MR3FAsU5G94d0KAru',69,'user',NULL),
('helen','n','helen@h.com','helen','$2b$10$SfdIbkeb5RcmTA5SHjJmSOEZWtkBNtLw5GuVlTHmxub1s1yynmIeO',70,'user','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzAsImlhdCI6MTc2OTQ0NDExMCwiZXhwIjoxNzcwMDQ4OTEwfQ.1WoE4_UuNQpemqego1l9BPrdT1_rCwSF7EbpO4BvsCg');

-- 4. Reset the identity sequence to ensure next insertions use the correct ID
SELECT setval(
    pg_get_serial_sequence('public.users', 'id'),
    COALESCE((SELECT MAX(id) FROM public.users), 1),
    true
);
